//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEntPlum
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Adam_AsprovaEntities1 : DbContext
    {
        public Adam_AsprovaEntities1()
            : base("name=Adam_AsprovaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<plum_logowania> plum_logowania { get; set; }
        public virtual DbSet<itZestawieniaPlum> itZestawieniaPlums { get; set; }
        public virtual DbSet<plum_pracownicy> plum_pracownicy { get; set; }
        public virtual DbSet<plum_uzytkownicy> plum_uzytkownicy_ { get; set; }
    
        public virtual int podajLogowaniaDnia(string dataShort)
        {
            var dataShortParameter = dataShort != null ?
                new ObjectParameter("dataShort", dataShort) :
                new ObjectParameter("dataShort", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("podajLogowaniaDnia", dataShortParameter);
        }
    
        public virtual int it_ZasilPlumDzien(Nullable<System.DateTime> czas)
        {
            var czasParameter = czas.HasValue ?
                new ObjectParameter("czas", czas) :
                new ObjectParameter("czas", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("it_ZasilPlumDzien", czasParameter);
        }
    }
}
