//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEntPlum
{
    using System;
    using System.Collections.Generic;
    
    public partial class plum_logowania
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string userName { get; set; }
        public string timeIn { get; set; }
        public string type { get; set; }
        public int prevId { get; set; }
        public int sessionId { get; set; }
        public string machineName { get; set; }
    }
}
